remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: David Lefor, Doctoral Researcher and International Development Specialist
description: Expertise in migration, youth, education, the HDP Nexus, gender, displacement-affected populations, qualitative and participatory research, and evidence-based policy for international organisations.
